apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: ulrichtraining
      - name: MYSQL_USER
        value: ulrich
      - name: MYSQL_PASSWORD
        value: ulrich
  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
      type: DirectoryOrCreate
